package registry

import "github.com/vpigadas/greek-tv-scraper/internal/model"

// Channels is the static channel registry.
// IDs match the XMLTV feed at https://ext.greektv.app/epg/epg.xml.gz exactly.
// ERT HLS URLs via akamaized.net are official and stable.
// Private channel HLS URLs change frequently — use LivePageURL as primary for non-ERT channels.
var Channels = []model.Channel{
	// ── ERT Public Broadcaster (stable HLS) ─────────────────────────────────
	{ID: "ert1", Name: "ERT1", Group: "ert", EPGSource: "ert",
		LogoURL: "https://program.ert.gr/images/ChannelLogo-ERT1.png",
		LiveURL: "https://ert-live-bcbs.akamaized.net/ert1hd/tracks-v1a1/mono.m3u8", LivePageURL: "https://www.ertflix.gr/live/ert1"},
	{ID: "ert2", Name: "ERT2", Group: "ert", EPGSource: "ert",
		LogoURL: "https://program.ert.gr/images/ChannelLogo-ERT2.png",
		LiveURL: "https://ert-live-bcbs.akamaized.net/ert2hd/tracks-v1a1/mono.m3u8", LivePageURL: "https://www.ertflix.gr/live/ert2"},
	{ID: "ert3", Name: "ERT3", Group: "ert", EPGSource: "ert",
		LogoURL: "https://program.ert.gr/images/ChannelLogo-ERT3.png",
		LiveURL: "https://ert-live-bcbs.akamaized.net/ert3hd/tracks-v1a1/mono.m3u8", LivePageURL: "https://www.ertflix.gr/live/ert3"},
	{ID: "ertsports", Name: "ERT Sports", Group: "ert", EPGSource: "ert",
		LogoURL:     "https://program.ert.gr/images/ChannelLogo-ERTSports.png",
		LivePageURL: "https://www.ertflix.gr/live/ert-sports"},
	{ID: "ertworld", Name: "ERT World", Group: "ert", EPGSource: "ert",
		LivePageURL: "https://www.ertflix.gr/live/ert-world"},
	{ID: "ertnews", Name: "ERT News", Group: "ert", EPGSource: "ert",
		LivePageURL: "https://www.ertflix.gr/live/ertnews"},
	{ID: "ertkids", Name: "ERT Kids", Group: "ert", EPGSource: "ert",
		LivePageURL: "https://www.ertflix.gr/live/ert-kids"},

	// ── National FTA ────────────────────────────────────────────────────────
	{ID: "ant1", Name: "ANT1", Group: "national", EPGSource: "digea",
		LivePageURL: "https://www.antenna.gr/live"},
	{ID: "mega", Name: "MEGA", Group: "national", EPGSource: "digea",
		LivePageURL: "https://www.megatv.com/live/"},
	{ID: "skai", Name: "SKAI", Group: "national", EPGSource: "digea",
		LivePageURL: "https://www.skai.gr/live"},
	{ID: "star", Name: "STAR", Group: "national", EPGSource: "digea",
		LivePageURL: "https://www.star.gr/live"},
	{ID: "alpha", Name: "Alpha", Group: "national", EPGSource: "digea",
		LivePageURL: "https://www.alphatv.gr/live"},
	{ID: "open", Name: "OPEN Beyond", Group: "national", EPGSource: "digea",
		LivePageURL: "https://www.opentv.gr/live"},
	{ID: "mtv", Name: "Makedonia TV", Group: "national", EPGSource: "digea",
		LivePageURL: "https://www.makedonia-tv.gr/live"},

	// ── Other National / Thematic FTA ───────────────────────────────────────
	{ID: "vouli", Name: "Vouli TV", Group: "national", EPGSource: "xmltv"},
	{ID: "action24", Name: "Action 24", Group: "national", EPGSource: "xmltv"},
	{ID: "atticatv", Name: "Attica TV", Group: "national", EPGSource: "xmltv"},
	{ID: "bluesky", Name: "Blue Sky", Group: "national", EPGSource: "xmltv"},
	{ID: "onetv", Name: "One TV", Group: "national", EPGSource: "xmltv"},
	{ID: "epsilon", Name: "Epsilon TV", Group: "national", EPGSource: "xmltv"},
	{ID: "hightv", Name: "High TV", Group: "national", EPGSource: "xmltv"},
	{ID: "kontra", Name: "Kontra Channel", Group: "national", EPGSource: "xmltv"},
	{ID: "madtv", Name: "MAD TV", Group: "national", EPGSource: "xmltv"},
	{ID: "risetv", Name: "Rise TV", Group: "national", EPGSource: "xmltv"},
	{ID: "nickelodeon", Name: "Nickelodeon", Group: "national", EPGSource: "xmltv"},
	{ID: "smile", Name: "Smile TV", Group: "national", EPGSource: "xmltv"},
	{ID: "alert", Name: "Alert TV", Group: "national", EPGSource: "xmltv"},
	{ID: "pronews", Name: "Pronews", Group: "national", EPGSource: "xmltv"},
	{ID: "4e", Name: "4E", Group: "national", EPGSource: "xmltv"},

	// ── Regional — Macedonia / Thrace ───────────────────────────────────────
	{ID: "alfa", Name: "Alfa TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "centertv", Name: "Center TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "deltatv", Name: "Delta TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "diktyotv", Name: "Diktyo TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "smileamth", Name: "Smile AM/TH", Group: "regional", EPGSource: "xmltv"},
	{ID: "enachannel", Name: "Ena Channel", Group: "regional", EPGSource: "xmltv"},
	{ID: "lydiatv", Name: "Lydia TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "orestiadatv", Name: "Orestiada TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "tvrodopi", Name: "TV Rodopi", Group: "regional", EPGSource: "xmltv"},
	{ID: "starbe", Name: "Star BE", Group: "regional", EPGSource: "xmltv"},
	{ID: "thrakinet", Name: "Thrakinet TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "tileepiloges", Name: "Tileepiloges", Group: "regional", EPGSource: "xmltv"},
	{ID: "nexttv", Name: "Next TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "tv100", Name: "TV100", Group: "regional", EPGSource: "xmltv"},
	{ID: "gnomitv", Name: "Gnomi TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "egnatia", Name: "Egnatia TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "pellatv", Name: "Pella TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "diktyo1", Name: "Diktyo 1", Group: "regional", EPGSource: "xmltv"},
	{ID: "flashtv", Name: "Flash TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "diontv", Name: "Dion TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "eurotv", Name: "Euro TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "atlastv", Name: "Atlas TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "berginatv", Name: "Bergina TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "europeone", Name: "Europe One", Group: "regional", EPGSource: "xmltv"},
	{ID: "epsilonthess", Name: "Epsilon Thess", Group: "regional", EPGSource: "xmltv"},
	{ID: "nickelodeonplus", Name: "Nickelodeon Plus", Group: "regional", EPGSource: "xmltv"},

	// ── Regional — Central / Western Greece ─────────────────────────────────
	{ID: "osiosnikanor", Name: "Osios Nikanor", Group: "regional", EPGSource: "xmltv"},
	{ID: "topchannel", Name: "Top Channel", Group: "regional", EPGSource: "xmltv"},
	{ID: "westchannel", Name: "West Channel", Group: "regional", EPGSource: "xmltv"},
	{ID: "arttv", Name: "ART TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "axelwostv", Name: "Axelwos TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "vimatv", Name: "Vima TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "thessaliatv", Name: "Thessalia TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "trt", Name: "TRT", Group: "regional", EPGSource: "xmltv"},
	{ID: "astratv", Name: "Astra TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "formediatv", Name: "For Media TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "smileplus", Name: "Smile Plus", Group: "regional", EPGSource: "xmltv"},
	{ID: "super", Name: "Super TV", Group: "regional", EPGSource: "xmltv"},

	// ── Regional — Epirus / Ionian ──────────────────────────────────────────
	{ID: "corfutv", Name: "Corfu TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "epirustv1", Name: "Epirus TV1", Group: "regional", EPGSource: "xmltv"},
	{ID: "itv", Name: "ITV", Group: "regional", EPGSource: "xmltv"},
	{ID: "starttv", Name: "Start TV", Group: "regional", EPGSource: "xmltv"},

	// ── Regional — Peloponnese ──────────────────────────────────────────────
	{ID: "achaiachannel", Name: "Achaia Channel", Group: "regional", EPGSource: "xmltv"},
	{ID: "artpel", Name: "ART Peloponnese", Group: "regional", EPGSource: "xmltv"},
	{ID: "axiontv", Name: "Axion TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "besttv", Name: "Best TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "ionian", Name: "Ionian TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "lepanto", Name: "Lepanto TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "lychnos", Name: "Lychnos TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "mesogeiostv", Name: "Mesogeios TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "anet", Name: "Anet TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "ort", Name: "ORT TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "patratv", Name: "Patra TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "rtpkentro", Name: "RTP Kentro", Group: "regional", EPGSource: "xmltv"},

	// ── Regional — Attica ───────────────────────────────────────────────────
	{ID: "notostv", Name: "Notos TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "etv", Name: "ETV", Group: "regional", EPGSource: "xmltv"},
	{ID: "enake", Name: "ENA KE", Group: "regional", EPGSource: "xmltv"},
	{ID: "starke", Name: "Star KE", Group: "regional", EPGSource: "xmltv"},
	{ID: "art", Name: "ART", Group: "regional", EPGSource: "xmltv"},
	{ID: "extrachannel", Name: "Extra Channel", Group: "regional", EPGSource: "xmltv"},

	// ── Regional — Crete ────────────────────────────────────────────────────
	{ID: "creta", Name: "Creta TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "krhthtv", Name: "Kriti TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "krititv1", Name: "Kriti TV1", Group: "regional", EPGSource: "xmltv"},
	{ID: "neatvcrete", Name: "Nea TV Crete", Group: "regional", EPGSource: "xmltv"},
	{ID: "sitiatv", Name: "Sitia TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "thlekriti", Name: "Tilekriti", Group: "regional", EPGSource: "xmltv"},

	// ── Regional — Aegean Islands ───────────────────────────────────────────
	{ID: "aigaiotv", Name: "Aigaio TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "kostv", Name: "Kos TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "iridatv", Name: "Irida TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "tharri", Name: "Tharri TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "samiakitv", Name: "Samiaki TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "kosmos", Name: "Kosmos TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "syrostv1", Name: "Syros TV1", Group: "regional", EPGSource: "xmltv"},
	{ID: "volcano", Name: "Volcano TV", Group: "regional", EPGSource: "xmltv"},

	// ── Regional — Lesbos / NE Aegean ───────────────────────────────────────
	{ID: "alithiatv", Name: "Alithia TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "patridatv", Name: "Patrida TV", Group: "regional", EPGSource: "xmltv"},
	{ID: "aeolos", Name: "Aeolos TV", Group: "regional", EPGSource: "xmltv"},

	// ── Cypriot ─────────────────────────────────────────────────────────────
	{ID: "rik1", Name: "RIK 1", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "rik2", Name: "RIK 2", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "rikhd", Name: "RIK HD", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "omega", Name: "Omega CY", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "ant1cy", Name: "ANT1 Cyprus", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "sigma", Name: "Sigma TV", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "alphacy", Name: "Alpha Cyprus", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "plustv", Name: "Plus TV", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "capitaltv", Name: "Capital TV", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "extracy", Name: "Extra CY", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "smiletvcy", Name: "Smile TV CY", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "berginacy", Name: "Bergina CY", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "omonoiatv", Name: "Omonoia TV", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "cytavisionsports1", Name: "Cytavision Sports 1", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "cytavisionsports2", Name: "Cytavision Sports 2", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "cytavisionsports3", Name: "Cytavision Sports 3", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "cytavisionsports4", Name: "Cytavision Sports 4", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "cytavisionsports5", Name: "Cytavision Sports 5", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "cytavisionsports6", Name: "Cytavision Sports 6", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "cytavisionsports7", Name: "Cytavision Sports 7", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "cytavisionsports8", Name: "Cytavision Sports 8", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "cytavisionsportspremierleague", Name: "Cytavision Premier League", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "cablenetsports1", Name: "Cablenet Sports 1", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "cablenetsports2", Name: "Cablenet Sports 2", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "cablenetsports3", Name: "Cablenet Sports 3", Group: "cypriot", EPGSource: "xmltv"},
	{ID: "smile tv cy", Name: "Smile TV CY (alt)", Group: "cypriot", EPGSource: "xmltv"},

	// ── News / International ────────────────────────────────────────────────
	{ID: "Euronews Greek", Name: "Euronews Greek", Group: "news", EPGSource: "xmltv"},
	{ID: "Naftemporikitv", Name: "Naftemporiki TV", Group: "news", EPGSource: "xmltv"},
	{ID: "Al Jazeera", Name: "Al Jazeera", Group: "news", EPGSource: "xmltv"},
	{ID: "DW", Name: "DW", Group: "news", EPGSource: "xmltv"},
	{ID: "Sky News", Name: "Sky News", Group: "news", EPGSource: "xmltv"},
	{ID: "BBC News", Name: "BBC News", Group: "news", EPGSource: "xmltv"},
	{ID: "CNN", Name: "CNN", Group: "news", EPGSource: "xmltv"},
	{ID: "CNBC", Name: "CNBC", Group: "news", EPGSource: "xmltv"},
	{ID: "meganews", Name: "Mega News", Group: "news", EPGSource: "xmltv"},

	// ── Diaspora / Satellite ────────────────────────────────────────────────
	{ID: "tv5", Name: "TV5 Monde", Group: "international", EPGSource: "xmltv"},
	{ID: "ant1europe", Name: "ANT1 Europe", Group: "international", EPGSource: "xmltv"},
	{ID: "ant1pacific", Name: "ANT1 Pacific", Group: "international", EPGSource: "xmltv"},
	{ID: "ant1sat", Name: "ANT1 Satellite", Group: "international", EPGSource: "xmltv"},
	{ID: "riksat", Name: "RIK Satellite", Group: "international", EPGSource: "xmltv"},
	{ID: "megacosmos", Name: "Mega Cosmos", Group: "international", EPGSource: "xmltv"},
	{ID: "starint", Name: "Star International", Group: "international", EPGSource: "xmltv"},
	{ID: "alphasatusa", Name: "Alpha Sat USA", Group: "international", EPGSource: "xmltv"},
	{ID: "alphasatcanada", Name: "Alpha Sat Canada", Group: "international", EPGSource: "xmltv"},
	{ID: "alphasataus", Name: "Alpha Sat Australia", Group: "international", EPGSource: "xmltv"},
	{ID: "alphasatdubai", Name: "Alpha Sat Dubai", Group: "international", EPGSource: "xmltv"},
	{ID: "sportpluseurope", Name: "Sport Plus Europe", Group: "international", EPGSource: "xmltv"},
	{ID: "sportplusaus", Name: "Sport Plus Australia", Group: "international", EPGSource: "xmltv"},
	{ID: "sportplususa", Name: "Sport Plus USA", Group: "international", EPGSource: "xmltv"},

	// ── Commercial: Cosmote Sport ───────────────────────────────────────────────
	{ID: "cosmote_sport_highlights", Name: "Cosmote Sport Highlights", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "cosmote_sport_1", Name: "Cosmote Sport 1", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "cosmote_sport_2", Name: "Cosmote Sport 2", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "cosmote_sport_3", Name: "Cosmote Sport 3", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "cosmote_sport_4", Name: "Cosmote Sport 4", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "cosmote_sport_5", Name: "Cosmote Sport 5", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "cosmote_sport_6", Name: "Cosmote Sport 6", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "cosmote_sport_7", Name: "Cosmote Sport 7", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "cosmote_sport_8", Name: "Cosmote Sport 8", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "cosmote_sport_9", Name: "Cosmote Sport 9", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "cosmote_sport_4k", Name: "Cosmote Sport 4K", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "cosmote_sport_aek", Name: "Cosmote Sport AEK", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "cosmote_sport_olympiacos", Name: "Cosmote Sport Olympiacos", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "cosmote_sport_panathinaikos", Name: "Cosmote Sport Panathinaikos", Group: "commercial-sport", EPGSource: "xmltv"},

	// ── Commercial: Nova Sport ──────────────────────────────────────────────────
	{ID: "novasportsnews", Name: "Nova Sports News", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "novasportspl", Name: "Nova Sports PL", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "novasportsstart", Name: "Nova Sports Start", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "novasportsprime", Name: "Nova Sports Prime", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "novasports1", Name: "Nova Sports 1", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "novasports2", Name: "Nova Sports 2", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "novasports3", Name: "Nova Sports 3", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "novasports4", Name: "Nova Sports 4", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "novasports5", Name: "Nova Sports 5", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "novasports6", Name: "Nova Sports 6", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "novasportsextra1", Name: "Nova Sports Extra 1", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "novasportsextra2", Name: "Nova Sports Extra 2", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "novasportsextra3", Name: "Nova Sports Extra 3", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "novasportsextra4", Name: "Nova Sports Extra 4", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "plus_sports_1", Name: "Plus Sports 1", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "plus_sports_2", Name: "Plus Sports 2", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "plus_sports_3", Name: "Plus Sports 3", Group: "commercial-sport", EPGSource: "xmltv"},

	// ── Commercial: Other Sport ─────────────────────────────────────────────────
	{ID: "Eurosport1", Name: "Eurosport 1", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "Eurosport2", Name: "Eurosport 2", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "Extreme Sports", Name: "Extreme Sports", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "GINX eSports", Name: "GINX eSports", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "Fight Network", Name: "Fight Network", Group: "commercial-sport", EPGSource: "xmltv"},
	{ID: "Padel Time", Name: "Padel Time", Group: "commercial-sport", EPGSource: "xmltv"},

	// ── Commercial: Cinema ──────────────────────────────────────────────────────
	{ID: "cosmote_cinema_1", Name: "Cosmote Cinema 1", Group: "commercial-cinema", EPGSource: "xmltv"},
	{ID: "cosmote_cinema_2", Name: "Cosmote Cinema 2", Group: "commercial-cinema", EPGSource: "xmltv"},
	{ID: "cosmote_cinema_3", Name: "Cosmote Cinema 3", Group: "commercial-cinema", EPGSource: "xmltv"},
	{ID: "novacinema1", Name: "Nova Cinema 1", Group: "commercial-cinema", EPGSource: "xmltv"},
	{ID: "novacinema2", Name: "Nova Cinema 2", Group: "commercial-cinema", EPGSource: "xmltv"},
	{ID: "novacinema3", Name: "Nova Cinema 3", Group: "commercial-cinema", EPGSource: "xmltv"},
	{ID: "novacinema4", Name: "Nova Cinema 4", Group: "commercial-cinema", EPGSource: "xmltv"},
	{ID: "novastars", Name: "Nova Stars", Group: "commercial-cinema", EPGSource: "xmltv"},
	{ID: "Village Cinema", Name: "Village Cinema", Group: "commercial-cinema", EPGSource: "xmltv"},
	{ID: "Movies Best HD", Name: "Movies Best HD", Group: "commercial-cinema", EPGSource: "xmltv"},
	{ID: "Greek Cinema", Name: "Greek Cinema", Group: "commercial-cinema", EPGSource: "xmltv"},
	{ID: "tcm", Name: "TCM", Group: "commercial-cinema", EPGSource: "xmltv"},
	{ID: "Epic Drama", Name: "Epic Drama", Group: "commercial-cinema", EPGSource: "xmltv"},

	// ── Commercial: Series / Entertainment ──────────────────────────────────────
	{ID: "cosmote series", Name: "Cosmote Series", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "cosmote series marathon", Name: "Cosmote Series Marathon", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "fx", Name: "FX", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "fx Life", Name: "FX Life", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "novalife", Name: "Nova Life", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "NovaSummer", Name: "Nova Summer", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "E!", Name: "E! Entertainment", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "TLC", Name: "TLC", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "FoodNetwork", Name: "Food Network", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "INPlus", Name: "IN Plus", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "Ant1 Comedy", Name: "ANT1 Comedy", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "Ant1 Drama", Name: "ANT1 Drama", Group: "commercial-other", EPGSource: "xmltv"},

	// ── Commercial: Documentary ─────────────────────────────────────────────────
	{ID: "COSMOTE HISTORY HD", Name: "Cosmote History HD", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "Discoverychannel", Name: "Discovery Channel", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "DiscoveryScience", Name: "Discovery Science", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "InvestigationDiscovery", Name: "Investigation Discovery", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "AnimalPlanet", Name: "Animal Planet", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "NationalGeographicChannel", Name: "National Geographic", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "NatGeoWild", Name: "Nat Geo Wild", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "HistoryChannel", Name: "History Channel", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "ViasatHistory", Name: "Viasat History", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "ViasatNature", Name: "Viasat Nature", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "ViasatExplore", Name: "Viasat Explore", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "Crime and Investigation", Name: "Crime & Investigation", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "BBCEarth", Name: "BBC Earth", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "Travel Channel", Name: "Travel Channel", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "HGTV", Name: "HGTV", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "Nautical Channel HD", Name: "Nautical Channel HD", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "Motorvision Channel HD", Name: "Motorvision Channel HD", Group: "commercial-other", EPGSource: "xmltv"},

	// ── Commercial: Kids ────────────────────────────────────────────────────────
	{ID: "Disney Channel", Name: "Disney Channel", Group: "commercial-kids", EPGSource: "xmltv"},
	{ID: "Disney Junior", Name: "Disney Junior", Group: "commercial-kids", EPGSource: "xmltv"},
	{ID: "Cartoon Network", Name: "Cartoon Network", Group: "commercial-kids", EPGSource: "xmltv"},
	{ID: "Cartoonito", Name: "Cartoonito", Group: "commercial-kids", EPGSource: "xmltv"},
	{ID: "ducktv", Name: "Duck TV", Group: "commercial-kids", EPGSource: "xmltv"},
	{ID: "BabyTV", Name: "Baby TV", Group: "commercial-kids", EPGSource: "xmltv"},
	{ID: "IDJKids", Name: "IDJ Kids", Group: "commercial-kids", EPGSource: "xmltv"},

	// ── Commercial: Music / Lifestyle ───────────────────────────────────────────
	{ID: "MAD Viral HD", Name: "MAD Viral HD", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "MAD GreekZ", Name: "MAD GreekZ", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "PanikTV", Name: "Panik TV", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "NR1", Name: "NR1", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "Stingray CMusic", Name: "Stingray CMusic", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "Stingray iConcerts", Name: "Stingray iConcerts", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "Luxe TV", Name: "Luxe TV", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "FTV", Name: "Fashion TV", Group: "commercial-other", EPGSource: "xmltv"},
	{ID: "MyZen TV", Name: "MyZen TV", Group: "commercial-other", EPGSource: "xmltv"},
}

// ChannelByID returns a pointer to a Channel by its EPG ID, or nil.
func ChannelByID(id string) *model.Channel {
	for i := range Channels {
		if Channels[i].ID == id {
			return &Channels[i]
		}
	}
	return nil
}
